# Generated by Django 2.2.10 on 2020-03-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
