# Generated by Django 2.2.10 on 2020-03-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_user'),
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='image.Image'),
        ),
    ]
