# Generated by Django 2.2.10 on 2020-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_guess_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
